# Create a folder
$ mkdir actions-runner && cd actions-runner
Copied! # Download the latest runner package
$ curl -o actions-runner-linux-arm64-2.321.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-arm64-2.321.0.tar.gz
# Optional: Validate the hash
$ echo "62cc5735d63057d8d07441507c3d6974e90c1854bdb33e9c8b26c0da086336e1  actions-runner-linux-arm64-2.321.0.tar.gz" | shasum -a 256 -c
# Extract the installer
$ tar xzf ./actions-runner-linux-arm64-2.321.0.tar.gz
Configure
# Create the runner and start the configuration experience
$ ./config.sh --url https://github.com/saltman007web/platform.prebuilts.gcc.darwin-x86.host.i686-apple-darwin-4.2.1 --token BMW3XZQ4QY5UVXVJL7SAYBLHOGCJS
# Last step, run it!
$ ./run.sh
Using your self-hosted runner
# Use this YAML in your workflow file for each job
runs-on: self-hosted
